# https://doc.traefik.io/traefik/reference/static-configuration/file/

###############################################################
# Global configuration
###############################################################

[global]
  checkNewVersion = true
  sendAnonymousUsage = true

###############################################################
# Input points configuration
###############################################################

# Definition of input points
#
[entryPoints]
  [entryPoints.web_secure]
    address = ":443"
    [entryPoints.web_secure.http]
      tls = {  }

  [entryPoints.web]
    address = ":80"
    # Permanent redirect to https
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "web_secure"
          scheme = "https"
          permanent = true
          priority = 1

###############################################################
# Traefik Log Configuration
###############################################################

# Traefik records
# Qualified by default and logged in Stdout
#
[log]

  # Registration level
  #
  # levels=TRACE, DEBUG, INFO, WARN, ERROR, FATAL, e PANIC
  #
  level = "DEBUG"

  # Defines the file path to the traefik log.If not specified, STDOUT will be used.
  # Intermediate directories are created if necessary.
  #
  # mkdir -p /var/log/traefik/
  #
  filePath = "/var/log/traefik/traefik.json"

  # The format is “json” or “common”.
  #
  # Optional
  # Default: "common"
  #
  format = "json"

  # Maximum log size
  # 100 mb
  #
  maxSize = 100

  # Maximum number of days to retain old log files based on the date/hour stamp
  # 30Dias
  #
  maxAge = 30

###############################################################
# Access Log Configuration
###############################################################

[accessLog]

  # Set the file path to the access log.If not specified, STDOUT will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  # mkdir -p /var/log/traefik/
  #
  filePath = "/var/log/traefik/access.log"

  # Format is either "json" or "common".
  #
  # Optional
  # Default: "common"
  #
  format = "json"

  # LOG NUMBER FOR LOG RECORDING
  # 100 lines
  #
  bufferingSize = 100

################################################################
# API and Panel Configuration
################################################################

# Enabling API and DASHBOARD
#
[api]
  # Enable the API in insecure mode
  #
  # Optional
  # Default: false
  #
  # insecure = true

  # Skilled panel
  #
  # Optional
  # Default: true
  #
  dashboard = true

# Enable ping
# [ping]

  # Related entry point name
  #
  # Optional
  # Default: "traefik"
  #
  # Path = /traefik
  # Methods = GET,HEAD
  # Description: An endpoint to verify the activity of the traefik process.Return a code 200 with the content: ok
  #
  # entryPoint = "traefik"

###############################################################
# Suppliers
###############################################################

[providers]
###############################################################
### FILE CONFIGURATION BACK
###############################################################

  # Enables the configuration back-end for archivo
  [providers.file]

  # Setup file patho
  # mkdir -p /etc/traefik/dynamic
  # cp ./dynamic/conf.toml ./etc/traefik/dynamic/conf.toml
  #
  filename = "/etc/traefik/dynamic/conf.toml"

  # Define Watch Option to True allow Traefik to automatically observe
  # File Changes
  #
  # Paddle: true
  #
  watch = true

###############################################################
### Docker configuration back-end
###############################################################

  # Enables the configuration back-end for docker swarm
  [providers.docker]
    # Documentation
    # https://doc.traefik.io/traefik/providers/swarm/#usebindportip
    #
    # useBindPortIP = true

    # Docker server endpoint.It can be a TCP or Unix socket Endpoint.
    #
    # Mandatory
    # Default: "unix:///var/run/docker.sock"
    #
    endpoint = "unix:///var/run/docker.sock"

    # Exposure containers by default in traefik
    #
    # Optional
    # Default: true
    #
    exposedByDefault = false

    # Defining the public communication network between containers
    #
    network = "local_network"

    # Watch Docker events.
    #
    # Default: true
    #
    watch = true

###############################################################
# Certificate Resolvers
###############################################################


[certificatesResolvers.letsencrypt_resolver.acme]
  # Email address used for registration.
  #
  # Mandatory
  #
  email = "cleber@codechat.dev"

  # File or key used for storage of certificates.
  # mkdir -p /etc/traefik/letsencrypt
  #
  # Mandatory
  #
  storage = "/etc/traefik/letsencrypt/acme.json"

  # useUmDesafioHttp01Acme.
  #
  # Optional
  #
  [certificatesResolvers.letsencrypt_resolver.acme.httpChallenge]
    entryPoint = "web"